### ISSUE TITLE
连接后无法正常运行及收发消息

### ISSUE THREAD

**Issue by 502milk** [2891954521/LiteLoaderQQNT-OneBotApi-JS#1]
![image](https://github.com/2891954521/LiteLoaderQQNT-OneBotApi-JS/assets/49502047/45db783c-af80-4a03-bb5d-2330832d2056)
![image](https://github.com/2891954521/LiteLoaderQQNT-OneBotApi-JS/assets/49502047/03edaca5-1ba1-473e-a9c8-0438c356bde2)
![image](https://github.com/2891954521/LiteLoaderQQNT-OneBotApi-JS/assets/49502047/9bc259d0-9dd3-4825-8236-eadbdd6a10e9)
接入koishi-adopt-onebot
日志如上图

![image](https://github.com/2891954521/LiteLoaderQQNT-OneBotApi-JS/assets/49502047/83b23a91-eb9f-4642-8d3a-3e8836ebdec9)
版本如上 

![image](https://github.com/2891954521/LiteLoaderQQNT-OneBotApi-JS/assets/49502047/f0131825-f558-45dc-85c7-ddeaa8e3f7c1)
接入mirai overflow后日志如图  直接断开

**Comment by 2891954521** [comment]
更新到 [v0.2.5](https://github.com/2891954521/LiteLoaderQQNT-OneBotApi-JS/releases/tag/v0.2.5) 试试
tiny_id的报错应该是你用的插件调用了频道的API，[源代码](https://github.com/koishijs/koishi-plugin-adapter-onebot/blob/74ec363eec977a8eb33fd05437c9e1ce1ff9c567/src/bot/index.ts#L49)
目前没有支持频道的打算，我没用过koishi，你可以试试在koishi里关掉频道功能

**Comment by 502milk** [comment]
显然不是注释一块一块代码就行了，太多了，放弃嘞 
mirai那边倒是不会断链了
