### ISSUE TITLE
[Bug] QQ 版本 9.9.12-25765 插件无法启动 配置页面空白

### ISSUE THREAD

**Issue by burningtnt** [2891954521/LiteLoaderQQNT-OneBotApi-JS#4]
![image](https://github.com/user-attachments/assets/39e7c70d-ab21-46a5-ab06-e80dfd45c41c)
如图。

![image](https://github.com/user-attachments/assets/b2ab8230-9b30-4b50-8989-dbcd3b15c78b)
![image](https://github.com/user-attachments/assets/40dc7457-9330-422b-a346-7c502a3dd039)

**Comment by 2891954521** [comment]
降一下LiteLoader版本试试

**Comment by burningtnt** [comment]
已尝试：LiteLoader 1.1.0 以来的版本，均无法正常显示配置界面。猜测为 QQ 版本所致。

由于其他插件，我无法降级 QQ。但我成功在 ./data/OneBotApi-JS 下查找到了 settings.json 配置文件。
我将用一些开发的经验将它修改

**Comment by burningtnt** [comment]
问题：我关闭 NTQQ 后，修改 settings.json 文件，再启动 NTQQ。之后访问 `http://127.0.0.1:8080/` 提示 `ERR_CONNECTION_REFUSED`

```json
{
    "http": {
        "enableServer": true,
        "port": 33000,
        "enable": true,
        "host": "http://127.0.0.1:8080/",
        "enableReport": true,
        "hosts": [
            "http://127.0.0.1:8080/"
        ]
    },
    "ws": {
        "enable": true,
        "host": "127.0.0.1",
        "port": 33001
    },
    "wsReverse": {
        "enable": false,
        "url": "",
        "apiUrl": "",
        "eventUrl": "",
        "useUniversalClient": false,
        "reconnectInterval": 3000
    },
    "setting": {
        "reportSelfMsg": true,
        "reportOldMsg": false,
        "autoAcceptFriendRequest": false
    },
    "misc": {
        "disableUpdate": true
    },
    "debug": {
        "debug": false,
        "ipc": false
    }
}
```

**Comment by 2891954521** [comment]
是qq版本的问题，插件应该没启动起来，怎么修我还没研究明白，可以临时先用QQ9.9.9

**Comment by 2891954521** [comment]
[v0.2.9](https://github.com/2891954521/LiteLoaderQQNT-OneBotApi-JS/releases/tag/v0.2.9) 可以在 QQ 9.9.12-25765 上正常运行
