### ISSUE TITLE
群成员列表获取中可以获取到所在地的信息吗

### ISSUE THREAD

**Issue by yuanjs2019** [2891954521/LiteLoaderQQNT-OneBotApi-JS#5]
群成员列表获取中可以获取到所在地的信息吗

**Comment by 2891954521** [comment]
可以加上，但是不能批量获取，只能按用户去获取

**Comment by 2891954521** [comment]
[v0.2.10](https://github.com/2891954521/LiteLoaderQQNT-OneBotApi-JS/releases/tag/v0.2.10)加上了，在get_group_member_info里，没有你想要的可以在raw字段里自己找
